config/routes.rb
Rails.application.routes.draw do
  
  resources :locations

  resources :comments

  get 'new/create'

  get 'new/destroy'

  get 'pages/home'

  get 'pages/about'

  resources :borroweds

  resources :books

  resources :members

  resources :branches
  
  resources :books do
		resources :comments
  end
  
  controller :sessions do
	get 'login' => :new
	post 'login' => :create
	get 'logout' => :destroy
	delete 'logout' => :destroy
  end

   root 'pages#home'

end

app/models/borrowed.rb
class Borrowed < ActiveRecord::Base
	belongs_to:member
	belongs_to:book
	validates:due_date, presence: true

end

app/controllers/borroweds_controller.rb
class BorrowedsController < ApplicationController
  before_action :set_borrowed, only: [:show, :edit, :update, :destroy]

  # GET /borroweds
  # GET /borroweds.json
  def index
    @borroweds = Borrowed.all
  end

  # GET /borroweds/1
  # GET /borroweds/1.json
  def show
  end

  # GET /borroweds/new
  def new
    @borrowed = Borrowed.new
  end

  # GET /borroweds/1/edit
  def edit
  end

  # POST /borroweds
  # POST /borroweds.json
  def create
    @borrowed = Borrowed.new(borrowed_params)

    respond_to do |format|
      if @borrowed.save
        format.html { redirect_to @borrowed, notice: 'Borrowed was successfully created.' }
        format.json { render :show, status: :created, location: @borrowed }
      else
        format.html { render :new }
        format.json { render json: @borrowed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /borroweds/1
  # PATCH/PUT /borroweds/1.json
  def update
    respond_to do |format|
      if @borrowed.update(borrowed_params)
        format.html { redirect_to @borrowed, notice: 'Borrowed was successfully updated.' }
        format.json { render :show, status: :ok, location: @borrowed }
      else
        format.html { render :edit }
        format.json { render json: @borrowed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /borroweds/1
  # DELETE /borroweds/1.json
  def destroy
    @borrowed.destroy
    respond_to do |format|
      format.html { redirect_to borroweds_url, notice: 'Borrowed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_borrowed
      @borrowed = Borrowed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def borrowed_params
      params.require(:borrowed).permit(:return_date, :date_due, :Member_id, :Book_id)
    end
end

app/helpers/borroweds_helper.rb
module BorrowedsHelper
end

app/views/borroweds/_form.html.erb
<%= form_for(@borrowed) do |f| %>
  <% if @borrowed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@borrowed.errors.count, "error") %> prohibited this borrowed from being saved:</h2>

      <ul>
      <% @borrowed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :return_date %><br>
    <%= f.date_select :return_date %>
  </div>
  <div class="field">
    <%= f.label :date_due %><br>
    <%= f.date_select :date_due %>
  </div>
  <div class="field">
    <%= f.label :Member_id %><br>
    <%= f.number_field :Member_id %>
  </div>
  <div class="field">
    <%= f.label :Book_id %><br>
    <%= f.number_field :Book_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/borroweds/edit.html.erb
<h1>Editing borrowed</h1>

<%= render 'form' %>

<%= link_to 'Show', @borrowed %> |
<%= link_to 'Back', borroweds_path %>

app/views/borroweds/index.html.erb
<h1>Listing borroweds</h1>

<table>
  <thead>
    <tr>
      <th>Return date</th>
      <th>Date due</th>
      <th>Member</th>
      <th>Book</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @borroweds.each do |borrowed| %>
      <tr>
        <td><%= borrowed.return_date %></td>
        <td><%= borrowed.date_due %></td>
        <td><%= borrowed.Member_id %></td>
        <td><%= borrowed.Book_id %></td>
        <td><%= link_to 'Show', borrowed %></td>
        <td><%= link_to 'Edit', edit_borrowed_path(borrowed) %></td>
        <td><%= link_to 'Destroy', borrowed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Borrowed', new_borrowed_path %>

app/views/borroweds/new.html.erb
<h1>New borrowed</h1>

<%= render 'form' %>

<%= link_to 'Back', borroweds_path %>

app/views/borroweds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Return date:</strong>
  <%= @borrowed.return_date %>
</p>

<p>
  <strong>Date due:</strong>
  <%= @borrowed.date_due %>
</p>

<p>
  <strong>Member:</strong>
  <%= @borrowed.Member_id %>
</p>

<p>
  <strong>Book:</strong>
  <%= @borrowed.Book_id %>
</p>

<%= link_to 'Edit', edit_borrowed_path(@borrowed) %> |
<%= link_to 'Back', borroweds_path %>